# Generated by Django 4.1.7 on 2023-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stories_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
